#!/bin/bash -e

source "${OPENSHIFT_RUBY_DIR}/lib/servers"

no-jruby

function start() {
  run_command "unicorn -c ${OPENSHIFT_REPO_DIR}/config/unicorn/production.rb -D -E production"
}

function stop() {
  kill -QUIT `cat ${OPENSHIFT_RUBY_DIR}run/server.pid`
}

function restart() {
  stop
  start
}

case "$1" in
  start)     start ;;
  stop)      stop ;;
  restart)   restart ;;
  *)         exit 0 ;;
esac